// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeTrackAndRestart(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetAV1Enabled():Promise<boolean>;

export function GetAnimeProgress(arg1:number):Promise<number>;

export function GetEcchiFilter():Promise<boolean>;

export function GetEpisodeTorrents(arg1:string,arg2:number):Promise<Array<main.TorrentResult>>;

export function GetMpvMetadata():Promise<main.FrontendPayload>;

export function GetOpusEnabled():Promise<boolean>;

export function GetResolution():Promise<main.Resolution>;

export function GetTranscoder():Promise<string>;

export function GetTrendingAnime():Promise<Array<main.Anime>>;

export function GetUpscaleMethod():Promise<string>;

export function GetUpscaleResolution():Promise<main.Resolution>;
export function GetUserWatchlist():Promise<Array<main.MediaList>>;

export function IsLoggedIn():Promise<boolean>;

export function LoginWithAniList():Promise<string>;

export function Logout():Promise<void>;

export function SearchAnime(arg1:string):Promise<Array<main.Anime>>;

export function SendMpvCommand(arg1:Array<any>):Promise<void>;

export function StopStream():Promise<void>;

export function StreamTorrent(arg1:string):Promise<string>;

export function UpdateAV1Enabled(arg1:boolean):Promise<void>;

export function UpdateAnimeProgress(arg1:number,arg2:number):Promise<void>;

export function UpdateEcchiFilter(arg1:boolean):Promise<void>;

export function UpdateOpusEnabled(arg1:boolean):Promise<void>;

export function UpdateResolution(arg1:number,arg2:number):Promise<void>;

export function UpdateTranscoder(arg1:string):Promise<void>;

export function UpdateUpscaleMethod(arg1:string):Promise<void>;

export function UpdateUpscaleResolution(arg1:main.Resolution):Promise<void>;
