// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetEpisodeTorrents(arg1:string,arg2:number):Promise<Array<main.TorrentResult>>;

export function GetTrendingAnime():Promise<Array<main.Anime>>;

export function MPVStream(arg1:string,arg2:string):Promise<string>;

export function SearchAnime(arg1:string):Promise<Array<main.Anime>>;

export function StreamTorrent(arg1:string):Promise<string>;
