// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAnimeProgress(arg1:number):Promise<number>;

export function GetEpisodeTorrents(arg1:string,arg2:number):Promise<Array<main.TorrentResult>>;

export function GetTrendingAnime():Promise<Array<main.Anime>>;

export function IsLoggedIn():Promise<boolean>;

export function LoginWithAniList():Promise<string>;

export function Logout():Promise<void>;

export function SearchAnime(arg1:string):Promise<Array<main.Anime>>;

export function StreamTorrent(arg1:string):Promise<string>;

export function UpdateAnimeProgress(arg1:number,arg2:number):Promise<void>;
