// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeTrackAndRestart(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeTrackAndRestart'](arg1, arg2, arg3);
}

export function GetAV1Enabled() {
  return window['go']['main']['App']['GetAV1Enabled']();
}

export function GetAnimeProgress(arg1) {
  return window['go']['main']['App']['GetAnimeProgress'](arg1);
}

export function GetEcchiFilter() {
  return window['go']['main']['App']['GetEcchiFilter']();
}

export function GetEpisodeTorrents(arg1, arg2) {
  return window['go']['main']['App']['GetEpisodeTorrents'](arg1, arg2);
}

export function GetFolder() {
  return window['go']['main']['App']['GetFolder']();
}

export function GetMpvMetadata() {
  return window['go']['main']['App']['GetMpvMetadata']();
}

export function GetOpusEnabled() {
  return window['go']['main']['App']['GetOpusEnabled']();
}

export function GetResolution() {
  return window['go']['main']['App']['GetResolution']();
}

export function GetSeasonalAnime() {
  return window['go']['main']['App']['GetSeasonalAnime']();
}

export function GetTranscoder() {
  return window['go']['main']['App']['GetTranscoder']();
}

export function GetTrendingAnime() {
  return window['go']['main']['App']['GetTrendingAnime']();
}

export function GetUpscaleMethod() {
  return window['go']['main']['App']['GetUpscaleMethod']();
}

export function GetUpscaleResolution() {
  return window['go']['main']['App']['GetUpscaleResolution']();
}

export function GetUserWatchlist() {
  return window['go']['main']['App']['GetUserWatchlist']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LoginWithAniList() {
  return window['go']['main']['App']['LoginWithAniList']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SearchAnime(arg1) {
  return window['go']['main']['App']['SearchAnime'](arg1);
}

export function SendMpvCommand(arg1) {
  return window['go']['main']['App']['SendMpvCommand'](arg1);
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}

export function StreamTorrent(arg1) {
  return window['go']['main']['App']['StreamTorrent'](arg1);
}

export function UpdateAV1Enabled(arg1) {
  return window['go']['main']['App']['UpdateAV1Enabled'](arg1);
}

export function UpdateAnimeProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateAnimeProgress'](arg1, arg2);
}

export function UpdateDownloadFolder(arg1) {
  return window['go']['main']['App']['UpdateDownloadFolder'](arg1);
}

export function UpdateEcchiFilter(arg1) {
  return window['go']['main']['App']['UpdateEcchiFilter'](arg1);
}

export function UpdateOpusEnabled(arg1) {
  return window['go']['main']['App']['UpdateOpusEnabled'](arg1);
}

export function UpdateResolution(arg1, arg2) {
  return window['go']['main']['App']['UpdateResolution'](arg1, arg2);
}

export function UpdateTranscoder(arg1) {
  return window['go']['main']['App']['UpdateTranscoder'](arg1);
}

export function UpdateUpscaleMethod(arg1) {
  return window['go']['main']['App']['UpdateUpscaleMethod'](arg1);
}

export function UpdateUpscaleResolution(arg1) {
  return window['go']['main']['App']['UpdateUpscaleResolution'](arg1);
}
