// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnimeProgress(arg1) {
  return window['go']['main']['App']['GetAnimeProgress'](arg1);
}

export function GetEpisodeTorrents(arg1, arg2) {
  return window['go']['main']['App']['GetEpisodeTorrents'](arg1, arg2);
}

export function GetResolution() {
  return window['go']['main']['App']['GetResolution']();
}

export function GetTrendingAnime() {
  return window['go']['main']['App']['GetTrendingAnime']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LoginWithAniList() {
  return window['go']['main']['App']['LoginWithAniList']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SearchAnime(arg1) {
  return window['go']['main']['App']['SearchAnime'](arg1);
}

export function StreamTorrent(arg1) {
  return window['go']['main']['App']['StreamTorrent'](arg1);
}

export function UpdateAnimeProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateAnimeProgress'](arg1, arg2);
}

export function UpdateResolution(arg1, arg2) {
  return window['go']['main']['App']['UpdateResolution'](arg1, arg2);
}
